{
 "title": "Seldon Deployment Monitoring 1",
 "tags": [ "seldon" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "deployment",
    "query": "label_values(seldon_api_executor_client_requests_seconds_count,deployment_name)"
   },
   {
    "name": "predictor",
    "query": "label_values(seldon_api_executor_client_requests_seconds_count,predictor_name)"
   },
   {
    "name": "version",
    "query": "label_values(seldon_api_executor_client_requests_seconds_count,predictor_version)"
   },
   {
    "name": "model_name",
    "query": "label_values(seldon_api_executor_client_requests_seconds_count,model_name)"
   },
   {
    "name": "model_image",
    "query": "label_values(seldon_api_executor_client_requests_seconds_count,model_image)"
   },
   {
    "name": "model_version",
    "query": "label_values(seldon_api_executor_client_requests_seconds_count,model_version)"
   }
  ]
 },
 "panels": [
  { "title": "Heading", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>Seldon Core API Dashboard</span>\n</div>"
  },
  { "title": "Global Counts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Global Request Rate - Server",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "round(sum(irate(seldon_api_executor_server_requests_seconds_count[1m])), 0.001)"
    }
   ]
  },
  {
   "title": "Global Request Rate - Sucess",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 5 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(seldon_api_executor_server_requests_seconds_count{status!~\"5.*\"}[1m])) / sum(rate(seldon_api_executor_server_requests_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "Global Request Rate - 4xxs Client Errors",
   "type": "singlestat",
   "description": "4xx client error – the request contains bad syntax or cannot be fulfilled",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 5 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(seldon_api_executor_server_requests_seconds_count{status=~\"4.*\"}[1m])) "
    }
   ]
  },
  {
   "title": "Global Rquest Rate 5xxs - Server Errors",
   "type": "singlestat",
   "description": "5xx server error – the server failed to fulfil an apparently valid request",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 5 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(seldon_api_executor_server_requests_seconds_count{status=~\"5.*\"}[1m])) "
    }
   ]
  },
  { "title": "Deployment Counts $deployment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "deployment" },
  {
   "title": "Request Rate ($deployment)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 9 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "round(sum(irate(seldon_api_executor_client_requests_seconds_count{deployment_name=~'$deployment'}[1m])), 0.001)"
    }
   ]
  },
  {
   "title": "Success ($deployment)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 9 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(seldon_api_executor_client_requests_seconds_count{deployment_name=~\"$deployment\",status!~\"5.*\"}[1m])) / sum(rate(seldon_api_executor_client_requests_seconds_count{deployment_name=~\"$deployment\"}[1m]))"
    }
   ]
  },
  {
   "title": "4xxs ($deployment)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 9 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(seldon_api_executor_client_requests_seconds_count{deployment_name=~\"$deployment\",status=~\"4.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "5xxs ($deployment)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 9 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(seldon_api_executor_client_requests_seconds_count{deployment_name=~\"$deployment\",status=~\"5.*\"}[1m]))"
    }
   ]
  },
  { "title": "Models", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 13 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>Models</span>\n</div>\n"
  },
  { "title": "Model Metrics $model_image", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 }, "repeat": "model_image" },
  {
   "title": "Reqs/sec to $model_image",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(seldon_api_executor_client_requests_seconds_count{model_name=~\"$model_name\",model_version=~\"$model_version\",model_image=~\"$model_image\",predictor_name=~\"$predictor\",predictor_version=~\"$version\"}[1m])) by (model_name,predictor_name,predictor_version,model_image,model_version,service)",
     "legendFormat": "{{predictor_name}}:{{predictor_version}} ({{model_name}} {{model_image}} : {{model_version}}) {{service}}"
    }
   ]
  },
  {
   "title": "$model_image Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(seldon_api_executor_client_requests_seconds_bucket{service=~\"/Predict\", model_image=~\"$model_image\",predictor_name=~\"$predictor\",predictor_version=~\"$version\",model_name=~\"$model_name\",model_version=~\"$model_version\"}[1m])) by (predictor_name,predictor_version,model_name,model_image,model_version,le))",
     "legendFormat": "{{predictor_name}}:{{predictor_version}} {{model_name}} {{model_image}}: {{model_version}} (p50)"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(seldon_api_executor_client_requests_seconds_bucket{service=~\".*[Pp]redict\",model_image=~\"$model_image\",predictor_name=~\"$predictor\",predictor_version=~\"$version\",model_name=~\"$model_name\",model_version=~\"$model_version\"}[1m])) by (predictor_name,predictor_version,model_name,model_image,model_version,service,le))",
     "legendFormat": "{{predictor_name}}:{{predictor_version}} {{model_name}} {{model_image}}:{{model_version}} {{service}} (p75)"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(seldon_api_executor_client_requests_seconds_bucket{service=~\".*[Pp]redict\",model_image=~\"$model_image\",predictor_name=~\"$predictor\",predictor_version=~\"$version\",model_name=~\"$model_name\",model_version=~\"$model_version\"}[1m])) by (predictor_name,predictor_version,model_name,model_image,model_version, service,le))",
     "legendFormat": "{{predictor_name}}:{{predictor_version}} {{model_name}} {{model_image}}:{{model_version}}  {{service}} (p90)"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(seldon_api_executor_client_requests_seconds_bucket{service=~\".*[Pp]redict\",model_image=~\"$model_image\",predictor_name=~\"$predictor\",predictor_version=~\"$version\",model_name=~\"$model_name\",model_version=~\"$model_version\"}[1m])) by (predictor_name,predictor_version,model_name,model_image,model_version,service,le))",
     "legendFormat": "{{predictor_name}}:{{predictor_version}} {{model_name}} {{model_image}}:{{model_version}} {{service}} (p95)"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(seldon_api_executor_client_requests_seconds_bucket{service=~\".*[Pp]redict\",model_image=~\"$model_image\",predictor_name=~\"$predictor\",predictor_version=~\"$version\",model_name=~\"$model_name\",model_version=~\"$model_version\"}[1m])) by (predictor_name,predictor_version,model_name,model_image,model_version,service,le))",
     "legendFormat": "{{predictor_name}}:{{predictor_version}} {{model_name}} {{model_image}}:{{model_version}} {{service}} (p99)"
    }
   ]
  },
  {
   "title": "CPU Usage $deployment",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "\nsum(rate(process_cpu_seconds_total{seldon_deployment_id=\"$deployment\"}[1m])) by (seldon_deployment_id, kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Residential Memory Usage $deployment",
   "type": "graph",
   "gridPos": { "h": 5, "w": 13, "x": 10, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{seldon_deployment_id=\"$deployment\"}) by (seldon_deployment_id, kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}