apiVersion: v1
data:
{{ (.Files.Glob "files/grafana/configs/seldon-deployment-monitoring-1.json").AsConfig | indent 2 }}
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: seldon-deployment-monitoring-1
  namespace: {{ .Release.Namespace }}
  labels:
    seldon_dashboard: "1"
